# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision "shell", path: "Initialize.sh"
  config.vm.hostname = "tedivm.com"
  config.vm.network :private_network, ip: "172.31.1.2"
  config.vm.synced_folder "../resources", "/resources"

end
